### ISSUE TITLE
Asset upload through ASC compatible component

### ISSUE THREAD

**Issue by deepkamal** [godanny86/sample-assetshare#2]
ASC provides a vibrant contemporary UI/UX to assets in DAM, however there is no equally exciting component which we can use to upload assets.

![image](https://user-images.githubusercontent.com/7984303/65943797-f83ef100-e44d-11e9-9b82-fbd668e0c77a.png)

with the help of dropzone.js we created a component that provides an upload drop zone where any asset can be dragged and dropped on browser and the component starts file upload to configured path. 

![image](https://user-images.githubusercontent.com/7984303/65943881-21f81800-e44e-11e9-90f3-ed95b6283295.png)

it also provides option of extensibility in form of JS methods to program pre-upload and post-upload actions.

Files being uploaded after drop on designated area:
![image](https://user-images.githubusercontent.com/7984303/65943997-5f5ca580-e44e-11e9-83a5-4dcfc5095211.png)

**Comment by godanny86** [comment]
hi @deepkamal very interesting issue! I would request you raise it on the main project: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues
